import { createClient } from '@supabase/supabase-js'

// These are read from environment variables.
// Create a .env.local file in your project root and add:
//   NEXT_PUBLIC_SUPABASE_URL=your_supabase_project_url
//   NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key

const supabaseUrl  = process.env.NEXT_PUBLIC_SUPABASE_URL  as string
const supabaseKey  = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY as string

if (!supabaseUrl || !supabaseKey) {
  throw new Error(
    'Missing Supabase environment variables.\n' +
    'Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY to your .env.local file.'
  )
}

export const supabase = createClient(supabaseUrl, supabaseKey)

// ============================================================
// DATABASE SCHEMA (run these in Supabase SQL Editor)
// ============================================================
//
// -- EVENTS TABLE
// create table public.events (
//   id          bigint generated by default as identity primary key,
//   title       text not null,
//   category    text not null,
//   date        date not null,
//   time        time not null,
//   location    text not null,
//   description text,
//   attendees   integer default 0,
//   created_at  timestamptz default now()
// );
//
// -- TIMETABLE TABLE
// create table public.timetable (
//   id          bigint generated by default as identity primary key,
//   subject     text not null,
//   type        text not null,
//   room        text,
//   lecturer    text,
//   start_time  time not null,
//   end_time    time not null,
//   day         text not null,
//   color       text default '#DBEAFE'
// );
//
// -- LOST & FOUND TABLE
// create table public.lost_found (
//   id          bigint generated by default as identity primary key,
//   title       text not null,
//   description text,
//   category    text,
//   status      text check (status in ('lost','found')) not null,
//   location    text not null,
//   date        date not null,
//   contact     text not null,
//   resolved    boolean default false,
//   created_at  timestamptz default now()
// );
//
// -- LOCATIONS TABLE (for campus map)
// create table public.locations (
//   id          bigint generated by default as identity primary key,
//   name        text not null,
//   category    text not null,
//   description text,
//   floor       text,
//   hours       text,
//   icon        text,
//   x_pos       numeric,  -- percentage 0-100 for map pin position
//   y_pos       numeric
// );
// ============================================================

export default supabase
